#
# To generate the whl files for mac arm64 on your local mac run
# python3 -m cibuildwheel --output-dir dist --platform macos --config-file {package}/pyproject_arm64.toml --archs arm64 .
#
# For this to work each version of python needs to be installed from https://www.python.org/downloads/macos/
# cibuildwheel will look for each version of python in /Library/Frameworks/Python.framework/Versions/
#
[build-system]
requires = [
    "setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel.macos]
archs = ["arm64"]
before-build = '''
# Update or install cmake
arch -arm64 brew upgrade cmake || arch -arm64 brew install cmake

arch -arm64 brew install boost fmt glog jpeg-turbo libpng lz4 xxhash zstd
'''
environment = {"ARCHFLAGS" ="-arch arm64", "CMAKE_ARGS"="-DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++"}
