#
# To generate the whl files for mac arm64 on your local mac run
# python3 -m cibuildwheel --output-dir dist --platform macos --config-file {package}/pyproject_arm64.toml --archs arm64 .
#
# For this to work each version of python needs to be installed from https://www.python.org/downloads/macos/
# cibuildwheel will look for each version of python in /Library/Frameworks/Python.framework/Versions/
#
[tool.cibuildwheel]
build="cp38-*64 cp39-*64 cp310-*64 cp311-*64"

[tool.cibuildwheel.macos]
archs = ["arm64"]
before-build='''
brew update && brew upgrade && arch -arm64 brew reinstall boost cmake fmt glog jpeg-turbo libpng

# Build lz4
git clone https://github.com/lz4/lz4.git
cd lz4
make
sudo make install
cd ..
rm -rf ./lz4

# Build zstd
git clone https://github.com/facebook/zstd.git
cd zstd
make
sudo make install
cd ..
rm -rf ./zstd

# Build xxhash
git clone https://github.com/Cyan4973/xxHash.git
cd xxHash
make
sudo make install
cd ..
rm -rf ./xxHash
'''
environment = {"ARCHFLAGS" ="-arch arm64", "CMAKE_ARGS"="-DCMAKE_OSX_DEPLOYMENT_TARGET=10.15  -DCMAKE_PREFIX_PATH=/Users/${USER}/homebrew -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++"}
